LangString addOrReinstall ${LANG_SIMPCHINESE} "补一下组件 / 重新装一遍"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已经准备好了"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已经在这台电脑上啦。选择接下来要做什么，然后点下一步继续。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 还在播放中。先关掉它，再来安装吧。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 还在运行。$\n点击确定，我来帮你结束它。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "要对 ${PRODUCTNAME} 做点什么？"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "选择 ${PRODUCTNAME} 的安装方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "不卸载，直接继续"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不卸载（当前安装器不允许直接降级）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "没能关闭 {{product_name}}。请手动关闭后再试一次。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在补齐 WebView2，马上就能开唱..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "这台电脑上已经有更新版本的 ${PRODUCTNAME}。不建议安装旧版本。如果确认要回到旧版本，建议先卸载当前版本。选择操作后点击下一步继续。"
LangString older ${LANG_SIMPCHINESE} "旧版本"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "检测到已安装 ${PRODUCTNAME} $R4。建议先卸载当前版本，再安装这一版。选择操作后点击下一步继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "当前安装器不支持静默降级，请打开安装界面手动确认。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "卸载失败了，请稍后再试。"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "先卸载旧版本，再安装这一版"
LangString unknown ${LANG_SIMPCHINESE} "未知版本"
LangString webview2AbortError ${LANG_SIMPCHINESE} "WebView2 安装失败。没有它，${PRODUCTNAME} 暂时无法运行。请重新打开安装器再试一次。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "WebView2 下载失败：$0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 下载完成。"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 运行环境..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "WebView2 安装失败，退出码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 已安装完成。"
LangString deleteAppData ${LANG_SIMPCHINESE} "同时删除应用数据"