package com.zheting.player

import androidx.core.content.FileProvider

/**
 * A distinct provider type keeps the poster-sharing URI namespace separate from
 * the FileProvider generated by the Tauri Android host application.
 */
class ZtShareFileProvider : FileProvider()
